image: python:3.9

stages:
  - test

before_script:
  - pip install scipy pytest

test:
  stage: test
  script:
    - pytest test_black_scholes.py -v

lint:
  stage: test
  script:
    - pip install flake8
    - flake8 black_scholes.py test_black_scholes.py

coverage:
  stage: test
  script:
    - pip install pytest-cov
    - pytest --cov=black_scholes test_black_scholes.py
    - pytest --cov=black_scholes --cov-report=xml test_black_scholes.py
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
