# .gitlab-ci.yml

# Use an official Python Docker image as the base for our jobs.
# python:3.9-slim is a good choice for consistency and smaller image size.
image: python:3.9-slim

# Define the stages of your CI/CD pipeline.
stages:
  - test

# Define the 'unit_tests' job within the 'test' stage.
unit_tests:
  stage: test # Assign this job to the 'test' stage
  script:
    # 1. Install project dependencies from requirements.txt
    - pip install -q -r requirements.txt

    # 2. Run your unit tests using the unittest discovery feature.
    - python -m unittest discover

  artifacts:
    paths:
      - . # Collect all files in the project directory as artifacts for inspection if needed
    expire_in: 1 week # How long to keep the artifacts